// OFFSETS
#define OFFSET_LOCALPLAYER 0xCFEFAC
#define OFFSET_ENTITYLIST 0xCB42D4
#define OFFSET_TARGETGUID 0xD65650

// LUA OFFSETS

#define LUA_DOSTRING 0x50236
#define LUA_GETLOCALIZEDTEXT 0x414C74

// FUNCTIONS
#define FUNC_GETPLAYEROBJ 0x4FC6
